import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
  } from "@/components/ui/accordion";
  import React from 'react';
  import { useNavigate } from 'react-router-dom';
  import { Button } from '../components/ui/button';
  import { useAuthContext } from "@/context/AuthContext";

  
  export default function FAQs() {
    
  const { authUser } = useAuthContext();
  const isAuthenticated = authUser ? true : false; // Adjusting based on the authUser state
    const navigate = useNavigate();
  
    const handleNavigateToSignUp = () => {
      navigate('/'); // Adjust the path to match your routes
    };
  
    return (
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Frequently Asked Questions</h1>
  
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="item-1">
              <AccordionTrigger>How does NewzSage verify news authenticity?</AccordionTrigger>
              <AccordionContent>
                NewzSage uses a combination of advanced AI models and community verification. Our machine learning algorithms analyze content patterns, sources, and cross-references, while our community provides additional validation through the voting system.
              </AccordionContent>
            </AccordionItem>
  
            <AccordionItem value="item-2">
              <AccordionTrigger>Can anyone publish news on NewzSage?</AccordionTrigger>
              <AccordionContent>
                Yes, but all content goes through our AI verification system and community review process. Publishers must also complete a verification process to establish their credibility.
              </AccordionContent>
            </AccordionItem>
  
            <AccordionItem value="item-3">
              <AccordionTrigger>What is the Accuracy Probability score?</AccordionTrigger>
              <AccordionContent>
                The Accuracy Probability score is a percentage-based metric generated by our AI system. It considers multiple factors including source credibility, cross-verification, and historical accuracy of the publisher.
              </AccordionContent>
            </AccordionItem>
  
            <AccordionItem value="item-4">
              <AccordionTrigger>How can I become a verified publisher?</AccordionTrigger>
              <AccordionContent>
                To become a verified publisher, you need to complete our verification process which includes identity verification, previous work portfolio review, and adherence to our publishing guidelines.
              </AccordionContent>
            </AccordionItem>
  
            <AccordionItem value="item-5">
              <AccordionTrigger>How does the community voting system work?</AccordionTrigger>
              <AccordionContent>
                Registered users can upvote or downvote news articles based on their accuracy and relevance. These votes contribute to the overall credibility score of both the article and the publisher.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
  
        {/* Centered Join Our Mission section */}
        {
            !isAuthenticated &&(
<div className="flex justify-center items-center bg-muted p-8 rounded-lg max-w-6xl mx-auto mt-12">
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-4">Join Our Mission</h2>
            <p className="mb-6">
              Be part of the movement to make news more transparent and accountable. Whether you're a publisher, fact-checker, or reader, there's a place for you in our community.
            </p>
            <Button size="lg" onClick={handleNavigateToSignUp}>Get Started Today</Button>
          </div>
        </div>
            )
        }
        
      </div>
    );
  }
  